from dotenv import load_dotenv
import os

load_dotenv()

ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
NAVER_APPLICATION_CLIENT_ID = os.getenv("NAVER_APPLICATION_CLIENT_ID")
NAVER_APPLICATION_CLIENT_SECRET = os.getenv("NAVER_APPLICATION_CLIENT_SECRET")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")